feat: random number generator
UNICT-Quality-Development/qd-starter-pack pull request #160
Opened 2023-10-30 17:44 UTC by 0xr3z

2023-10-30 17:47 UTC, infra-blue requested changes

2023-10-30 17:47 UTC, infra-blue commented on src/random-number.py
> +'''
rimuovi questa stringa

2023-10-30 17:56 UTC, 0xr3z commented on src/random-number.py
> +'''
Fatto grazie mille, a quanto pare non gli piacevano i commenti multi-line

2023-10-31 09:01 UTC, simone989 commented on src/random-number.py
> +import random
Importa solo la funzione randint dal modulo random.

2023-10-31 09:01 UTC, simone989 commented on src/random-number.py
> +number = int(random.randrange(0,1000))
Definisci sempre i valori costanti in opportune variabili.

```
MIN_NUMBER=0
MAX_NUMBER= 1_000
```

2024-03-27 17:40 UTC, closed without merging