Random number
UNICT-Quality-Development/qd-starter-pack pull request #178
Opened 2023-11-08 17:47 UTC by SCsimoc98

Aggiunta funzione per generare numeri interi randomici e test da 0 a 100

2023-11-08 17:55 UTC, TendTo requested changes

2023-11-08 17:55 UTC, TendTo commented on src/random_number.py
> +def random_number(min: int, max: int) -> int:
Il nome delle variabili in questa maniera e' estremamente esplicito, pero' c'e' il problema che vanno a sovrascrivere (e quindi nascondere) le funzioni built-in di python, `max` e `min`, che quindi non potresti andare ad utilizzare all'interno della funzione.
Potresti quindi optare per nomi alternativi come `min_value` o `minimum` o `puffo`. Magari non l'ultimo. A meno che tu non sia Barbanera.

2023-11-08 17:55 UTC, TendTo commented on tests/test_random_number.py
> +    assert t >= 0 and t <= 100
Volendo potresti mettere questo test in un ciclo giusto per fargli fare un po' di passate e vedere piu' output, ma essendo random in principio non cambia tantissimo

2023-11-09 08:35 UTC, simone989 commented on tests/test_random_number.py
> +    t = random_number(0, 100)
Dai un nome più "parlante" alla variabile `t`.
In questo contesto è ovviamente semplice da capire cosa contiene ma non è sempre così.

2023-11-09 08:35 UTC, simone989 commented on tests/test_random_number.py
> +    t = random_number(0, 100)
Definisci delle variabili costanti che contengano 0 e 100.

2023-11-28 19:12 UTC, closed without merging