feat: Risiko implementato
UNICT-Quality-Development/qd-starter-pack pull request #67
Opened 2022-11-10 10:56 UTC by MeloFuccio

Come semplificare il codice?
Come sistemare i vari if con un un for con indice?

2022-11-10 11:35 UTC, aegroto requested changes
oltre ai commenti che ti ho fatto rileggi il codice e vedi dove puoi mettere a fattor comune linee di codice simili in una funzione a parte, richiamandola ove necessario.

2022-11-10 11:35 UTC, aegroto commented on src/risk-risiko.py
> +    atk_dice_n = random.randint(1,6)
crea una funzione che effettua il lancio del dado e ritorna il valore invece di ripetere la chiamata a randint con gli stessi parametri

2022-11-10 11:35 UTC, aegroto commented on src/risk-risiko.py
> +    atk_dice_n = random.randint(1,6)
vedendo il codice sotto, credo che sia comodo avere una funzione che calcoli il valore di n dadi:

random_dice_run(n)

e ritorna una tupla di n elementi.

potresti in questo modo riutilizzare la stessa funzione anche per il difensore, tanto ciò che cambia non è il lancio di dadi ma il confronto.

2022-11-10 11:35 UTC, aegroto commented on src/risk-risiko.py
> +    print ("Rolling attacker (blue) dices.. \n")
questo dovrebbe essere "defender"

2022-11-10 11:35 UTC, aegroto commented on src/risk-risiko.py
> +    if attacker_dices[0] <= defender_dices[0]:
questo dovrebbe essere un for. 

fossi in te farei una funzione a parte che prende le 2 tuple attacker_dices e defender_dices e ritorni il vincitore, in questo modo è anche più facile scriverci dei test perché puoi passare dei valori dei dati specifici senza dover generare valori random.

2022-11-11 11:58 UTC, Helias commented on src/risk-risiko.py
> +      break
questo non serve

2022-11-11 11:59 UTC, Helias commented on src/risk-risiko.py
> +      print(tanks[x],atk[x]," vs ",defn[x], "=> Blue team wins")
nei due if ciò che cambia è solo "Blue" o "Red", metti la print sotto e quel "Blue" o "Red" mettilo in una variabile es.
```python
if ...:
  team_win = "red"
else:
 team_win = "blue"
 
 
 print(tanks[x],atk[x]," vs ",defn[x], "=>", team_win , " team wins")
 ```

2022-11-11 15:01 UTC, Helias commented
correggi ciò che ti segnala pylint

2023-10-22 09:26 UTC, closed without merging